name: Run Tests

on:
  pull_request:
    branches: [2.x] # or the branches you want to protect

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # or your actual Python version

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run migrations
      #   run: python manage.py migrate

      # - name: Start backend server
      #   run: |
      #     nohup python manage.py runserver 0.0.0.0:80 &
      #     sleep 10 # Wait for the server to start
      - name: run app
        run: |
          source venv/bin/activate
          ./scripts/start-linkace.sh
      - name: Wait for app to be ready
        run: |
          sleep 10 # Adjust the sleep time as necessary for your app to be ready
          
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests_wajdi 